### ISSUE TITLE
No condaforge release available

### ISSUE THREAD

**Issue by arm61** [reflectivity/orsopy#102]
Currently `orsopy` is only available on PyPI, to support everyone we should also make it available on `condaforge`

**Comment by rbauststfc** [comment]
Hi @andyfaff, I'm one of the Mantid software developers at ISIS. We're currently trying to implement the ORSO ASCII file in Mantid using the `orsopy` library. I'm afraid we're going to need the library to be available on `condaforge` when we get to the point of being ready to release our change. I noticed you were assigned to this issue, is there any update on progress with this? Thanks very much.

**Comment by andyfaff** [comment]
Its really annoying, I've had a staged recipe for ages and the conda-forge admin haven't got around to merging it. I ping them every now and then. https://github.com/conda-forge/staged-recipes/pull/22770

**Comment by rbauststfc** [comment]
Thanks for the update - I'm sorry to hear there's been such a delay getting the recipe merged, that is very frustrating. Thanks very much for trying to get this all sorted.

**Comment by andyfaff** [comment]
Please checkout https://github.com/conda-forge/orsopy-feedstock, it should be available from conda-forge now. Help on maintaining orsopy/orsopy-feedstock would always be appreciated ;-).

**Comment by bmaranville** [comment]
Now that the initial merge is complete, do we need to do a PR every time we want to update the recipe?

**Comment by arm61** [comment]
@rbauststfc I am curious why there is the decision in mantid not to let anything be installed via pip?

**Comment by andyfaff** [comment]
> Now that the initial merge is complete, do we need to do a PR every time we want to update the recipe?

Sort of, yes. The conda forge mechanism picks up if there are new GitHub releases for orsopy, and automakes a PR for new orsopy versions. When it makes the PR it rerenders the recipe.

We can do everything manually as well. Manual intervention is required if we want to change which tests run, etc.

On the whole the recipe process is simple-ish, you won't have toi many frustrations.

**Comment by rbauststfc** [comment]
> @rbauststfc I am curious why there is the decision in mantid not to let anything be installed via pip?

We find it creates some difficulties with the Mantid Conda packages we make available. This isn't my area of expertise I'm afraid, but hopefully [this](https://www.github.com/mantidproject/mantid/issues/36152) helps to explain.
