### ISSUE TITLE
Problems with pip install using python 3.7

### ISSUE THREAD

**Issue by tomarnoldess** [reflectivity/orsopy#106]
Hiro Aoki has been trying to install orsopy at J-Parc. He sent me the following emails:

> When I try to install orsopy by pip, it says:
> ERROR: Could not find a version that satisfies the requirement orsopy
> ERROR: No matching distribution found for orsopy
> The data reduction system in SHARAKU uses Python 3.7.
> Does orsopy support it?
> Does orsopy works on Python 3.7 if it is installed by downloading
> the tarball and running a setup script?

and then
> I installed orsopy from tarball on Docker container of python:3.7-slim .
> The sample code worked on it.
> But I am not sure that all functions are OK.
> I would appreciate the information.
> If orsopy works on Python <=3.7, I would appreciate it if you could make the installation with PIP possible also for older versions of Python.

**Comment by bmaranville** [comment]
Apparently in our testing we're doing this for python 3.6 and 3.7, which seems a little weird (we test that it works in those versions, but we require version 3.8 or higher?  Why are we testing then?)

https://github.com/reflectivity/orsopy/blob/efd3abba588934425f7436f348d3adfec140e10a/.github/workflows/pytest.yml#L67

**Comment by arm61** [comment]
The tests are labelled "backport". I think that this was something @aglavic added.

**Comment by andyfaff** [comment]
`setup.cfg` has been on 3.8 since 94b7cfc30ee4d9da32f45bb8a42f7e9989926957. Can SHARAKU update their Python version? Alternatively can they install as @bmaranville suggests?
3.7 is out of security updates after June this month (https://peps.python.org/pep-0537/#lifespan)

**Comment by aglavic** [comment]
This was our compromise to support old python versions that are at end-of-lift. The pip installation does not work out of the box as the python version does not match for 3.6/3.7. We re testing this as I think it's important to support those, even if we do so non-officially.
I would be fine to officially support this versions, but that's a group decision. I'm against forcing people to update their systems just out of principle if not required by technology.

With these you need to add "--ignore-requires-python" to pip, then it should work out of the box. Just tested it with py36 and everything seems to work.

I think you can close this issue @arm61 .

**Comment by bmaranville** [comment]
I vote to update the python requirements in the setup to include 3.6, 3.7 if we are going to test and support these older versions.  Forcing people to jump through hoops to install orsopy isn't going to help us or them.
