### ISSUE TITLE
In `measurement`, `polarization` is nominally mandatory, but is not automatically included as a field

### ISSUE THREAD

**Issue by jfkcooper** [reflectivity/orsopy#110]
All other mandatory fields for the standard are auto populated with a `null` if left unwritten. `Polarization` is different in that it is an enum rather than a "free" field, but this is still inconsistent behaviour. not sure what the best default even could be - the obvious choice is `unpolarized` but this could be very misleading. Discussion on this is very welcome

**Comment by andyfaff** [comment]
```
from orsopy.fileio import Orso, Value, ValueRange, InstrumentSettings
ia = Value(0.5)
wl = ValueRange(2.8, 20)
iset = InstrumentSettings(ia, wl)

print(iset.polarization)
```

gives `None`. I would assume that a polarization of None would equate to unpolarized. We could change the constructor of InstrumentSettings to be 'unpolarized' by default.
