### ISSUE TITLE
Use python types in Header class attributes

### ISSUE THREAD

**Issue by bmaranville** [reflectivity/orsopy#55]
https://github.com/reflectivity/orsopy/blob/7472fd6553651911c14af4b12c49cb59bc463d9c/orsopy/fileio/orso.py#L97
Is there an objection to changing
```python
Class OrsoDataset:
    ...
    data: np.ndarray
```
to 
```python
Class OrsoDataset:
    ...
    data: Union[List[List[float]], List[List[int]]]
```
so that we can use the orsopy read/write library to generate the yaml and json schemas?  This is the only place that we are using a non-python type, preventing us from integrating the schema fully with the python code base.

**Comment by bmaranville** [comment]
The schema generation is recursive - it finds the OrsoDataset from where it is referenced in the other classes.  It is not something being manually added.  There are ways to address this - I fixed the issue in the pull request #57 by creating a custom __init__.

**Comment by arm61** [comment]
Can this be closed @bmaranville?

**Comment by aglavic** [comment]
> it finds the OrsoDataset from where it is referenced in the other classes
That's what I meant, OrsoDataset should not be referenced anywhere in the other classes, as it is the container that combined data with header information. The Orso class is what defines the header and thus the schema.

**Comment by bmaranville** [comment]
I would like to try again to auto-generate the schema but only after PR #61 is re-applied.  I think it was overwritten in a force push.

**Comment by andyfaff** [comment]
Do you mean that all the commits from #61 were lost? That's not good. @aglavic, do you know where the changes in #61 went to, is there a way of retrieving them/reapplying them?

**Comment by bmaranville** [comment]
They're still stored on the github website (in the PR history) they're just not in the main history anymore.  I think we can recover them from the (closed merged) PR.

**Comment by andyfaff** [comment]
> I think we can recover them from the (closed merged) PR.

Can you do that?

**Comment by bmaranville** [comment]
I think I understand what @aglavic is saying above - and I agree, if I generate the schema from the Orso class and not OrsoDataset class, I believe it will work.

This issue can be closed.
