### ISSUE TITLE
Person vs Creator nomenclature difference.

### ISSUE THREAD

**Issue by andyfaff** [reflectivity/orsopy#6]
The `tests/test_example.ort` file has a `'creator'` key. However, if I look at the `orsopy.fileio.orso.Orso` class one of the attributes is a`DataSource` instance. `DataSource` has an `owner` attribute, which is a `Person` instance.

Should the *ort* file replace `'creator'` by `'owner'`?
-or-
Should the `DataSource` object have a `creator` attribute.

I'm trying to think through how to create an ORSO object from the dict that results from the parse yaml header. I would expect the yaml keys to match 1:1 with the ORSO dataclass names/attributes.

**Comment by arm61** [comment]
My logic was that there is `owner` in `DataSource` and `creator` in `Reduction` (however I think now the `creator` should actually be in `Orso` instead based on the latest information online. But the point was that the `Person` class can be used for both and the tag in the yaml will be whatever the attribute is in the class.

**Comment by andyfaff** [comment]
So should `Orso` or `DataSource` have a `creator` attribute?

**Comment by andyfaff** [comment]
The dict created from parsing the yaml on that file has:
```
>>> dct.keys()
dict_keys(['creator', 'data_source', 'reduction', 'columns', 'data set'])
```
the ORSO dataclass has:
```
    data_source: DataSource
    measurement: Measurement
    reduction: Reduction
    column_description: List[Column]
    data_set: int
```

Is it wrong of me to expect a 1:1 correspondence between those keys and the attributes? (e.g. `measurement` appears to be under `data_source` in the ort file)

**Comment by arm61** [comment]
I was putting it together based on this https://www.reflectometry.org/projects/file_formats/tasks/ws_2021-06_text/ (or what it was like at some point). I don't know if the test file matches the current standard as defined on the webpage.
