### ISSUE TITLE
Inconsistency in Orso.empty() - first column must be Qz

### ISSUE THREAD

**Issue by bmaranville** [reflectivity/orsopy#67]
Currently Orso.empty() creates a header object with empty.columns == [Column.empty()] == [Column(name=None)]

This is inconsistent with our agreed-upon specification, which requires that any existing columns up to length 4 must be named in this order: ["Qz", "R", "sR", "sQz"], and any columns after that can have any name.

Mitigations we can use include:

1. modify Column.empty() (or Orso.empty()?) to output columns == None instead of [Column(name=None)]
2. modify Column.empty() to output something like [Column(name="Qz")] or [Column(name="Qz"), Column(name="R")]
3. drop the rule about column order from the specification
4. not enforce the rule about column order in the schema

What do people think we should do?

**Comment by andyfaff** [comment]
I'd like 3 and 4 to be non-starters. In real life would an empty file (or one without data having been filled in) ever be useful to save and recover?
If the answer is yes, and since I'd like to keep our existing specification, and things have to make sense, then would it be best to go with 1?

**Comment by bmaranville** [comment]
I'm ok with 1 - it's the solution I used in the original pull request.  But I don't know how Orso.empty() is intended to be used - if users are going to get one of these and fill it out, then putting in the minimal column set (Qz, R) might be helpful.
If it's only ever going to be used by other programs as a starting point, then it doesn't really matter and we can just pick one and move on.
