### ISSUE TITLE
more specific half-polarized identifiers

### ISSUE THREAD

**Issue by bmaranville** [reflectivity/orsopy#82]
@pkienzle is suggesting that polarization outputs from reduction for half-polarized experiments should indicate which half is polarized, e.g. ```?+``` for the case where the incident beam is unpolarized and the reflected beam is ```+```.  Then ```?+``` and ```+?``` would replace our current ```+``` polarization (similarly for ```-```)

If you are going to base your modeling on this information, there are some instances where it is important to know which spin-flip channel is being folded implicitly into your data.

I guess our list of polarizations would then be ```[?+, +?, ?-, -?, --, -+, +-, ++]``` (not sure if we should also retain the ```+``` and ```-``` options)

**Comment by arm61** [comment]
I like this idea. I wish `\pm` was in the ASCII character set, but `?` works.

**Comment by bmaranville** [comment]
I thought about "u" and "0" to mark it as well, but I think Paul's suggestion of ? works the best ("+0" looks weird, and "u" suggests "unpolarized" which is not exactly what we're indicating)

**Comment by arm61** [comment]
Yeah I am happy with `?`

**Comment by aglavic** [comment]
This has been implemented in the recent updates of the specification #85 .
