### ISSUE TITLE
How to release new features between official ORSO approved specification versions

### ISSUE THREAD

**Issue by aglavic** [reflectivity/orsopy#89]
I discussed with @jochenstahn about the way we can implement new features to be tested e.g. at beamlines in a way that is installable from pip but does not interfere with the ORSO defined standard file header. (e.g. the simple model language)

I haven't looked at the technical details, but I think it should be possible to release bug-fixes as "stable" and these new features as "beta" on PyPI so that normal installation should only take the stable versions. 

I would propose to create a "beta" or "dev" branch on this repository and modify the release action to automatically build the beta branch tags as PyPI beta release and the main branch as stable release.

**Do you think this is a viable way forward?**

**Comment by arm61** [comment]
Why not pip install directly from GitHub? For example, if my beamline requires that I install from pip but I have a new feature in `my_cool_feature` branch then I install with 

```
pip install https://github.com/reflectivity/orsopy.git@my_cool_feature
```

and it should install the version from this branch.

**Comment by bmaranville** [comment]
I think if you pip install from https it has to point to an archive directly

**Comment by bmaranville** [comment]
You can do ```pip install git+https://...``` but that requires that git be installed in a way that plays nice with pip.  Thought that is often the case.

**Comment by arm61** [comment]
I accidentally read the question for this instead of the answer (couldn't remember the extra syntax)! You are right https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by arm61** [comment]
The installation from git (if it is robust enough) means that we could have more than one development branch at a time.

**Comment by bmaranville** [comment]
Installation from git will be a lot easier than trying to manage things in the pypi infrastructure (unless you're really good at that sort of thing, which I am not)

**Comment by andyfaff** [comment]
git+https:// is the way to go here. Either that or put it onto testpypi
